### ISSUE TITLE
python2 to python3 issue

### ISSUE THREAD

**Issue by guille-okt** [munkireport/laps#20]
File "/usr/local/munkireport/scripts/macOSLAPS", line 95, in make_random_password
    characters = characters.translate(None, remove_pass_characters)

TypeError: str.translate() takes exactly one argument (2 given)

**Comment by guille-okt** [comment]
Running macOSLAPS
    macOSLAPS Error: Traceback (most recent call last):
  File "/usr/local/munkireport/scripts/macOSLAPS", line 284, in password_check
    stored_plist = plistlib.readPlist('/var/root/.mrlaps')
AttributeError: module 'plistlib' has no attribute 'readPlist'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/munkireport/scripts/macOSLAPS", line 336, in <module>
    LAPS.password_check()
  File "/usr/local/munkireport/scripts/macOSLAPS", line 287, in password_check
    stored_plist = plistlib.load('/var/root/.mrlaps')
  File "/Library/ManagedFrameworks/Python/Python3.framework/Versions/3.10/lib/python3.10/plistlib.py", line 861, in load
    header = fp.read(32)
AttributeError: 'str' object has no attribute 'read'
WARNING: macOSLAPS return code: 1

**Comment by tuxudo** [comment]
This should be fixed in v3.1 of the module.

**Comment by guille-okt** [comment]
ok, testing the changes

**Comment by guille-okt** [comment]
Running macOSLAPS
    macOSLAPS Error: Traceback (most recent call last):
    File "/usr/local/munkireport/scripts/macOSLAPS", line 330, in <module>
    LAPS.password_check()
    File "/usr/local/munkireport/scripts/macOSLAPS", line 114, in password_check
    password = LAPS.make_random_password(pass_length)
    File "/usr/local/munkireport/scripts/macOSLAPS", line 95, in make_random_password
    characters = characters.translate( { ord(i): None for i in remove_pass_characters} )
    File "/usr/local/munkireport/scripts/macOSLAPS", line 95, in <dictcomp>
    characters = characters.translate( { ord(i): None for i in remove_pass_characters} )
    TypeError: ord() expected string of length 1, but int found
    WARNING: macOSLAPS return code: 1`

**Comment by tuxudo** [comment]
Should be fixed in v3.2 of the module, fixed a few other decoding issues as well. Wasn't until after I released the new version that I saw your PR to fix it :(
